apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages-redis
  labels:
    app: messages-redis
spec:
  selector:
    matchLabels:
      app: messages-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: messages-redis
    spec:
      containers:
        - name: messages-redis
          image: redis
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 300Mi
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: messages-redis
  labels:
    app: messages-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: messages-redis
