// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/messages.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessagesError struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessagesError) Reset()         { *m = MessagesError{} }
func (m *MessagesError) String() string { return proto.CompactTextString(m) }
func (*MessagesError) ProtoMessage()    {}
func (*MessagesError) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{0}
}

func (m *MessagesError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagesError.Unmarshal(m, b)
}
func (m *MessagesError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagesError.Marshal(b, m, deterministic)
}
func (m *MessagesError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesError.Merge(m, src)
}
func (m *MessagesError) XXX_Size() int {
	return xxx_messageInfo_MessagesError.Size(m)
}
func (m *MessagesError) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesError.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesError proto.InternalMessageInfo

func (m *MessagesError) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *MessagesError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type MessageBackendApproveRequest struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageBackendApproveRequest) Reset()         { *m = MessageBackendApproveRequest{} }
func (m *MessageBackendApproveRequest) String() string { return proto.CompactTextString(m) }
func (*MessageBackendApproveRequest) ProtoMessage()    {}
func (*MessageBackendApproveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{1}
}

func (m *MessageBackendApproveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageBackendApproveRequest.Unmarshal(m, b)
}
func (m *MessageBackendApproveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageBackendApproveRequest.Marshal(b, m, deterministic)
}
func (m *MessageBackendApproveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageBackendApproveRequest.Merge(m, src)
}
func (m *MessageBackendApproveRequest) XXX_Size() int {
	return xxx_messageInfo_MessageBackendApproveRequest.Size(m)
}
func (m *MessageBackendApproveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageBackendApproveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageBackendApproveRequest proto.InternalMessageInfo

func (m *MessageBackendApproveRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type MessageBackendApproveResponse struct {
	Valid                bool           `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Error                *MessagesError `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MessageBackendApproveResponse) Reset()         { *m = MessageBackendApproveResponse{} }
func (m *MessageBackendApproveResponse) String() string { return proto.CompactTextString(m) }
func (*MessageBackendApproveResponse) ProtoMessage()    {}
func (*MessageBackendApproveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{2}
}

func (m *MessageBackendApproveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageBackendApproveResponse.Unmarshal(m, b)
}
func (m *MessageBackendApproveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageBackendApproveResponse.Marshal(b, m, deterministic)
}
func (m *MessageBackendApproveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageBackendApproveResponse.Merge(m, src)
}
func (m *MessageBackendApproveResponse) XXX_Size() int {
	return xxx_messageInfo_MessageBackendApproveResponse.Size(m)
}
func (m *MessageBackendApproveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageBackendApproveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageBackendApproveResponse proto.InternalMessageInfo

func (m *MessageBackendApproveResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *MessageBackendApproveResponse) GetError() *MessagesError {
	if m != nil {
		return m.Error
	}
	return nil
}

type MessageBackendDeliverRequest struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageBackendDeliverRequest) Reset()         { *m = MessageBackendDeliverRequest{} }
func (m *MessageBackendDeliverRequest) String() string { return proto.CompactTextString(m) }
func (*MessageBackendDeliverRequest) ProtoMessage()    {}
func (*MessageBackendDeliverRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{3}
}

func (m *MessageBackendDeliverRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageBackendDeliverRequest.Unmarshal(m, b)
}
func (m *MessageBackendDeliverRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageBackendDeliverRequest.Marshal(b, m, deterministic)
}
func (m *MessageBackendDeliverRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageBackendDeliverRequest.Merge(m, src)
}
func (m *MessageBackendDeliverRequest) XXX_Size() int {
	return xxx_messageInfo_MessageBackendDeliverRequest.Size(m)
}
func (m *MessageBackendDeliverRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageBackendDeliverRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageBackendDeliverRequest proto.InternalMessageInfo

func (m *MessageBackendDeliverRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type MessageBackendDeliverResponse struct {
	Error                *MessagesError `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MessageBackendDeliverResponse) Reset()         { *m = MessageBackendDeliverResponse{} }
func (m *MessageBackendDeliverResponse) String() string { return proto.CompactTextString(m) }
func (*MessageBackendDeliverResponse) ProtoMessage()    {}
func (*MessageBackendDeliverResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{4}
}

func (m *MessageBackendDeliverResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageBackendDeliverResponse.Unmarshal(m, b)
}
func (m *MessageBackendDeliverResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageBackendDeliverResponse.Marshal(b, m, deterministic)
}
func (m *MessageBackendDeliverResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageBackendDeliverResponse.Merge(m, src)
}
func (m *MessageBackendDeliverResponse) XXX_Size() int {
	return xxx_messageInfo_MessageBackendDeliverResponse.Size(m)
}
func (m *MessageBackendDeliverResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageBackendDeliverResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageBackendDeliverResponse proto.InternalMessageInfo

func (m *MessageBackendDeliverResponse) GetError() *MessagesError {
	if m != nil {
		return m.Error
	}
	return nil
}

type Message struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Channel              string   `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Provider             string   `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{5}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Message) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *Message) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *Message) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Message) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type Channel struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Providers            []*Provider `protobuf:"bytes,2,rep,name=providers,proto3" json:"providers,omitempty"`
	Host                 string      `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port                 string      `protobuf:"bytes,4,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Channel) Reset()         { *m = Channel{} }
func (m *Channel) String() string { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()    {}
func (*Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{6}
}

func (m *Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Channel.Unmarshal(m, b)
}
func (m *Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Channel.Marshal(b, m, deterministic)
}
func (m *Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Channel.Merge(m, src)
}
func (m *Channel) XXX_Size() int {
	return xxx_messageInfo_Channel.Size(m)
}
func (m *Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_Channel proto.InternalMessageInfo

func (m *Channel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Channel) GetProviders() []*Provider {
	if m != nil {
		return m.Providers
	}
	return nil
}

func (m *Channel) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Channel) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type Provider struct {
	Name                 string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Params               map[string]*any.Any `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Provider) Reset()         { *m = Provider{} }
func (m *Provider) String() string { return proto.CompactTextString(m) }
func (*Provider) ProtoMessage()    {}
func (*Provider) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{7}
}

func (m *Provider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Provider.Unmarshal(m, b)
}
func (m *Provider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Provider.Marshal(b, m, deterministic)
}
func (m *Provider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Provider.Merge(m, src)
}
func (m *Provider) XXX_Size() int {
	return xxx_messageInfo_Provider.Size(m)
}
func (m *Provider) XXX_DiscardUnknown() {
	xxx_messageInfo_Provider.DiscardUnknown(m)
}

var xxx_messageInfo_Provider proto.InternalMessageInfo

func (m *Provider) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Provider) GetParams() map[string]*any.Any {
	if m != nil {
		return m.Params
	}
	return nil
}

type MessagePutRequest struct {
	Channel              string   `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Provider             string   `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Delay                int64    `protobuf:"varint,4,opt,name=delay,proto3" json:"delay,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessagePutRequest) Reset()         { *m = MessagePutRequest{} }
func (m *MessagePutRequest) String() string { return proto.CompactTextString(m) }
func (*MessagePutRequest) ProtoMessage()    {}
func (*MessagePutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{8}
}

func (m *MessagePutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagePutRequest.Unmarshal(m, b)
}
func (m *MessagePutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagePutRequest.Marshal(b, m, deterministic)
}
func (m *MessagePutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagePutRequest.Merge(m, src)
}
func (m *MessagePutRequest) XXX_Size() int {
	return xxx_messageInfo_MessagePutRequest.Size(m)
}
func (m *MessagePutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagePutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessagePutRequest proto.InternalMessageInfo

func (m *MessagePutRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *MessagePutRequest) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *MessagePutRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MessagePutRequest) GetDelay() int64 {
	if m != nil {
		return m.Delay
	}
	return 0
}

type MessagePutDataResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessagePutDataResponse) Reset()         { *m = MessagePutDataResponse{} }
func (m *MessagePutDataResponse) String() string { return proto.CompactTextString(m) }
func (*MessagePutDataResponse) ProtoMessage()    {}
func (*MessagePutDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{9}
}

func (m *MessagePutDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagePutDataResponse.Unmarshal(m, b)
}
func (m *MessagePutDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagePutDataResponse.Marshal(b, m, deterministic)
}
func (m *MessagePutDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagePutDataResponse.Merge(m, src)
}
func (m *MessagePutDataResponse) XXX_Size() int {
	return xxx_messageInfo_MessagePutDataResponse.Size(m)
}
func (m *MessagePutDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagePutDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessagePutDataResponse proto.InternalMessageInfo

func (m *MessagePutDataResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MessagePutResponse struct {
	Data                 *MessagePutDataResponse `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                *MessagesError          `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *MessagePutResponse) Reset()         { *m = MessagePutResponse{} }
func (m *MessagePutResponse) String() string { return proto.CompactTextString(m) }
func (*MessagePutResponse) ProtoMessage()    {}
func (*MessagePutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{10}
}

func (m *MessagePutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagePutResponse.Unmarshal(m, b)
}
func (m *MessagePutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagePutResponse.Marshal(b, m, deterministic)
}
func (m *MessagePutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagePutResponse.Merge(m, src)
}
func (m *MessagePutResponse) XXX_Size() int {
	return xxx_messageInfo_MessagePutResponse.Size(m)
}
func (m *MessagePutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagePutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessagePutResponse proto.InternalMessageInfo

func (m *MessagePutResponse) GetData() *MessagePutDataResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *MessagePutResponse) GetError() *MessagesError {
	if m != nil {
		return m.Error
	}
	return nil
}

type MessageGetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageGetRequest) Reset()         { *m = MessageGetRequest{} }
func (m *MessageGetRequest) String() string { return proto.CompactTextString(m) }
func (*MessageGetRequest) ProtoMessage()    {}
func (*MessageGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{11}
}

func (m *MessageGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageGetRequest.Unmarshal(m, b)
}
func (m *MessageGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageGetRequest.Marshal(b, m, deterministic)
}
func (m *MessageGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageGetRequest.Merge(m, src)
}
func (m *MessageGetRequest) XXX_Size() int {
	return xxx_messageInfo_MessageGetRequest.Size(m)
}
func (m *MessageGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageGetRequest proto.InternalMessageInfo

func (m *MessageGetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MessageGetResponse struct {
	Data                 *Message       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                *MessagesError `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MessageGetResponse) Reset()         { *m = MessageGetResponse{} }
func (m *MessageGetResponse) String() string { return proto.CompactTextString(m) }
func (*MessageGetResponse) ProtoMessage()    {}
func (*MessageGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{12}
}

func (m *MessageGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageGetResponse.Unmarshal(m, b)
}
func (m *MessageGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageGetResponse.Marshal(b, m, deterministic)
}
func (m *MessageGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageGetResponse.Merge(m, src)
}
func (m *MessageGetResponse) XXX_Size() int {
	return xxx_messageInfo_MessageGetResponse.Size(m)
}
func (m *MessageGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageGetResponse proto.InternalMessageInfo

func (m *MessageGetResponse) GetData() *Message {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *MessageGetResponse) GetError() *MessagesError {
	if m != nil {
		return m.Error
	}
	return nil
}

type MessageUpdateRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageUpdateRequest) Reset()         { *m = MessageUpdateRequest{} }
func (m *MessageUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*MessageUpdateRequest) ProtoMessage()    {}
func (*MessageUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{13}
}

func (m *MessageUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageUpdateRequest.Unmarshal(m, b)
}
func (m *MessageUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageUpdateRequest.Marshal(b, m, deterministic)
}
func (m *MessageUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageUpdateRequest.Merge(m, src)
}
func (m *MessageUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_MessageUpdateRequest.Size(m)
}
func (m *MessageUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageUpdateRequest proto.InternalMessageInfo

func (m *MessageUpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageUpdateRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type MessageUpdateResponse struct {
	Error                *MessagesError `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MessageUpdateResponse) Reset()         { *m = MessageUpdateResponse{} }
func (m *MessageUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*MessageUpdateResponse) ProtoMessage()    {}
func (*MessageUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{14}
}

func (m *MessageUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageUpdateResponse.Unmarshal(m, b)
}
func (m *MessageUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageUpdateResponse.Marshal(b, m, deterministic)
}
func (m *MessageUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageUpdateResponse.Merge(m, src)
}
func (m *MessageUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_MessageUpdateResponse.Size(m)
}
func (m *MessageUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageUpdateResponse proto.InternalMessageInfo

func (m *MessageUpdateResponse) GetError() *MessagesError {
	if m != nil {
		return m.Error
	}
	return nil
}

type MessageCancelRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageCancelRequest) Reset()         { *m = MessageCancelRequest{} }
func (m *MessageCancelRequest) String() string { return proto.CompactTextString(m) }
func (*MessageCancelRequest) ProtoMessage()    {}
func (*MessageCancelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{15}
}

func (m *MessageCancelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageCancelRequest.Unmarshal(m, b)
}
func (m *MessageCancelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageCancelRequest.Marshal(b, m, deterministic)
}
func (m *MessageCancelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageCancelRequest.Merge(m, src)
}
func (m *MessageCancelRequest) XXX_Size() int {
	return xxx_messageInfo_MessageCancelRequest.Size(m)
}
func (m *MessageCancelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageCancelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageCancelRequest proto.InternalMessageInfo

func (m *MessageCancelRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MessageCancelResponse struct {
	Error                *MessagesError `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MessageCancelResponse) Reset()         { *m = MessageCancelResponse{} }
func (m *MessageCancelResponse) String() string { return proto.CompactTextString(m) }
func (*MessageCancelResponse) ProtoMessage()    {}
func (*MessageCancelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{16}
}

func (m *MessageCancelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageCancelResponse.Unmarshal(m, b)
}
func (m *MessageCancelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageCancelResponse.Marshal(b, m, deterministic)
}
func (m *MessageCancelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageCancelResponse.Merge(m, src)
}
func (m *MessageCancelResponse) XXX_Size() int {
	return xxx_messageInfo_MessageCancelResponse.Size(m)
}
func (m *MessageCancelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageCancelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageCancelResponse proto.InternalMessageInfo

func (m *MessageCancelResponse) GetError() *MessagesError {
	if m != nil {
		return m.Error
	}
	return nil
}

type MessageRegisterRequest struct {
	Channel              *Channel `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRegisterRequest) Reset()         { *m = MessageRegisterRequest{} }
func (m *MessageRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*MessageRegisterRequest) ProtoMessage()    {}
func (*MessageRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{17}
}

func (m *MessageRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRegisterRequest.Unmarshal(m, b)
}
func (m *MessageRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRegisterRequest.Marshal(b, m, deterministic)
}
func (m *MessageRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRegisterRequest.Merge(m, src)
}
func (m *MessageRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_MessageRegisterRequest.Size(m)
}
func (m *MessageRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRegisterRequest proto.InternalMessageInfo

func (m *MessageRegisterRequest) GetChannel() *Channel {
	if m != nil {
		return m.Channel
	}
	return nil
}

type MessageRegisterResponse struct {
	Error                *MessagesError `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MessageRegisterResponse) Reset()         { *m = MessageRegisterResponse{} }
func (m *MessageRegisterResponse) String() string { return proto.CompactTextString(m) }
func (*MessageRegisterResponse) ProtoMessage()    {}
func (*MessageRegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{18}
}

func (m *MessageRegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRegisterResponse.Unmarshal(m, b)
}
func (m *MessageRegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRegisterResponse.Marshal(b, m, deterministic)
}
func (m *MessageRegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRegisterResponse.Merge(m, src)
}
func (m *MessageRegisterResponse) XXX_Size() int {
	return xxx_messageInfo_MessageRegisterResponse.Size(m)
}
func (m *MessageRegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRegisterResponse proto.InternalMessageInfo

func (m *MessageRegisterResponse) GetError() *MessagesError {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*MessagesError)(nil), "proto.MessagesError")
	proto.RegisterType((*MessageBackendApproveRequest)(nil), "proto.MessageBackendApproveRequest")
	proto.RegisterType((*MessageBackendApproveResponse)(nil), "proto.MessageBackendApproveResponse")
	proto.RegisterType((*MessageBackendDeliverRequest)(nil), "proto.MessageBackendDeliverRequest")
	proto.RegisterType((*MessageBackendDeliverResponse)(nil), "proto.MessageBackendDeliverResponse")
	proto.RegisterType((*Message)(nil), "proto.Message")
	proto.RegisterType((*Channel)(nil), "proto.Channel")
	proto.RegisterType((*Provider)(nil), "proto.Provider")
	proto.RegisterMapType((map[string]*any.Any)(nil), "proto.Provider.ParamsEntry")
	proto.RegisterType((*MessagePutRequest)(nil), "proto.MessagePutRequest")
	proto.RegisterType((*MessagePutDataResponse)(nil), "proto.MessagePutDataResponse")
	proto.RegisterType((*MessagePutResponse)(nil), "proto.MessagePutResponse")
	proto.RegisterType((*MessageGetRequest)(nil), "proto.MessageGetRequest")
	proto.RegisterType((*MessageGetResponse)(nil), "proto.MessageGetResponse")
	proto.RegisterType((*MessageUpdateRequest)(nil), "proto.MessageUpdateRequest")
	proto.RegisterType((*MessageUpdateResponse)(nil), "proto.MessageUpdateResponse")
	proto.RegisterType((*MessageCancelRequest)(nil), "proto.MessageCancelRequest")
	proto.RegisterType((*MessageCancelResponse)(nil), "proto.MessageCancelResponse")
	proto.RegisterType((*MessageRegisterRequest)(nil), "proto.MessageRegisterRequest")
	proto.RegisterType((*MessageRegisterResponse)(nil), "proto.MessageRegisterResponse")
}

func init() { proto.RegisterFile("proto/messages.proto", fileDescriptor_346d92f49d8efbd3) }

var fileDescriptor_346d92f49d8efbd3 = []byte{
	// 708 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x8e, 0x9d, 0xff, 0xa9, 0x28, 0xb0, 0x0a, 0xc5, 0x4d, 0x5b, 0x54, 0x6d, 0x11, 0x8a, 0x90,
	0x48, 0x45, 0x7a, 0xa9, 0x50, 0x91, 0xe8, 0x4f, 0xd4, 0x43, 0x85, 0x88, 0x8c, 0xe0, 0xbe, 0x8d,
	0x87, 0x34, 0xaa, 0x6b, 0x1b, 0x7b, 0x13, 0x29, 0x47, 0xde, 0x85, 0x77, 0xe1, 0x51, 0x78, 0x0d,
	0xe4, 0xf5, 0xd8, 0xf1, 0x3a, 0x31, 0x55, 0x7b, 0xca, 0x8e, 0x77, 0xe6, 0x9b, 0x6f, 0x67, 0xbe,
	0x99, 0x40, 0x27, 0x08, 0x7d, 0xe9, 0x1f, 0xde, 0x61, 0x14, 0x89, 0x09, 0x46, 0x7d, 0x65, 0xb2,
	0xba, 0xfa, 0xe9, 0x6e, 0x4f, 0x7c, 0x7f, 0xe2, 0xe2, 0xa1, 0xb2, 0xae, 0x67, 0x3f, 0x0e, 0x85,
	0xb7, 0x48, 0x3c, 0xf8, 0x47, 0x78, 0xf2, 0x99, 0x62, 0x86, 0x61, 0xe8, 0x87, 0x8c, 0x41, 0x6d,
	0xec, 0x3b, 0x68, 0x19, 0xfb, 0x46, 0xaf, 0x6e, 0xab, 0x33, 0xb3, 0xa0, 0x49, 0xc0, 0x96, 0xb9,
	0x6f, 0xf4, 0xda, 0x76, 0x6a, 0xf2, 0x63, 0xd8, 0xa5, 0xf0, 0x33, 0x31, 0xbe, 0x45, 0xcf, 0x39,
	0x0d, 0x82, 0xd0, 0x9f, 0xa3, 0x8d, 0x3f, 0x67, 0x18, 0xc9, 0x38, 0x72, 0xec, 0x7b, 0x12, 0x3d,
	0xa9, 0x00, 0xdb, 0x76, 0x6a, 0x72, 0x01, 0x7b, 0x25, 0x91, 0x51, 0xe0, 0x7b, 0x11, 0xb2, 0x0e,
	0xd4, 0xe7, 0xc2, 0x9d, 0x3a, 0x2a, 0xb0, 0x65, 0x27, 0x06, 0x7b, 0x0b, 0x75, 0x8c, 0x79, 0x2a,
	0x22, 0x1b, 0x83, 0x4e, 0xf2, 0x8c, 0xbe, 0xf6, 0x06, 0x3b, 0x71, 0x59, 0x25, 0x77, 0x81, 0xee,
	0x74, 0x8e, 0xe1, 0xfd, 0xe4, 0xae, 0x8a, 0xe4, 0xb2, 0x48, 0x22, 0x97, 0xd1, 0x30, 0xee, 0xa7,
	0xf1, 0xcb, 0x80, 0x26, 0x5d, 0xb0, 0x4d, 0x30, 0xe9, 0x45, 0x6d, 0xdb, 0x9c, 0x3a, 0x8a, 0xc2,
	0x8d, 0xf0, 0x3c, 0x74, 0xd3, 0xca, 0x92, 0xc9, 0xba, 0xd0, 0x8a, 0xeb, 0x31, 0x75, 0x30, 0xb4,
	0xaa, 0xea, 0x2a, 0xb3, 0xf3, 0xc4, 0x6b, 0x1a, 0x71, 0xb6, 0x05, 0x8d, 0x48, 0x0a, 0x39, 0x8b,
	0xac, 0xba, 0xba, 0x20, 0x8b, 0x4b, 0x68, 0x9e, 0x13, 0x30, 0x83, 0x9a, 0x27, 0xee, 0x90, 0x48,
	0xa8, 0x33, 0x7b, 0x07, 0xed, 0x14, 0x3c, 0xb2, 0xcc, 0xfd, 0x6a, 0x6f, 0x63, 0xf0, 0x94, 0x9e,
	0x34, 0xa2, 0xef, 0xf6, 0xd2, 0x23, 0x86, 0xb8, 0xf1, 0x23, 0x49, 0xbc, 0xd4, 0x39, 0xfe, 0x16,
	0xf8, 0x61, 0x4a, 0x48, 0x9d, 0xf9, 0x6f, 0x03, 0x5a, 0x69, 0xfc, 0xda, 0xbc, 0x47, 0xd0, 0x08,
	0x44, 0x28, 0xee, 0xd2, 0xa4, 0x3b, 0x85, 0xa4, 0xfd, 0x91, 0xba, 0x1d, 0x7a, 0x32, 0x5c, 0xd8,
	0xe4, 0xda, 0xfd, 0x02, 0x1b, 0xb9, 0xcf, 0xec, 0x19, 0x54, 0x6f, 0x71, 0x41, 0xb0, 0xf1, 0x31,
	0x6e, 0xce, 0x5c, 0xb8, 0x33, 0xcc, 0x34, 0x92, 0xc8, 0xbf, 0x9f, 0xca, 0xbf, 0x7f, 0xea, 0x2d,
	0xec, 0xc4, 0xe5, 0x83, 0x79, 0x6c, 0xf0, 0x05, 0x3c, 0xa7, 0xfe, 0x8c, 0x66, 0x32, 0x2f, 0x0e,
	0xea, 0x8c, 0x51, 0xde, 0x19, 0xb3, 0xbc, 0x33, 0x55, 0xbd, 0x33, 0x1d, 0xa8, 0x3b, 0xe8, 0x8a,
	0x85, 0x2a, 0x50, 0xd5, 0x4e, 0x0c, 0xde, 0x83, 0xad, 0x65, 0xea, 0x0b, 0x21, 0x45, 0xa6, 0xb0,
	0x82, 0x52, 0x78, 0x04, 0x2c, 0x4f, 0x92, 0xbc, 0xde, 0x43, 0xcd, 0x11, 0x52, 0x90, 0x0c, 0xf7,
	0x74, 0x19, 0x16, 0x20, 0x6d, 0xe5, 0xfa, 0xa0, 0x09, 0x3a, 0xc8, 0x2a, 0x73, 0x89, 0x59, 0x65,
	0x8a, 0xcc, 0x9c, 0x8c, 0x99, 0x72, 0x22, 0x66, 0x5c, 0x63, 0xb6, 0xa9, 0x67, 0x79, 0x04, 0x95,
	0x4f, 0xd0, 0xa1, 0xef, 0xdf, 0x02, 0x47, 0x48, 0x2c, 0x61, 0x93, 0xef, 0x80, 0xa9, 0x0f, 0xf5,
	0x39, 0xbc, 0x28, 0x20, 0x3c, 0x62, 0x98, 0xdf, 0x64, 0x34, 0xce, 0x85, 0x37, 0x46, 0xb7, 0xac,
	0x28, 0xcb, 0x64, 0xa9, 0xdf, 0x23, 0x92, 0x9d, 0x65, 0xea, 0xb0, 0x71, 0x32, 0x8d, 0xe4, 0x72,
	0x75, 0xf5, 0x74, 0x75, 0x2e, 0x0b, 0x4c, 0x53, 0x9e, 0xa9, 0x95, 0x0f, 0xe1, 0xe5, 0x0a, 0xc6,
	0xc3, 0xa9, 0x0c, 0xfe, 0x18, 0xd9, 0x83, 0x68, 0x25, 0x7e, 0xc5, 0x70, 0x3e, 0x1d, 0x23, 0xfb,
	0x0e, 0x4d, 0x5a, 0xdd, 0xec, 0x40, 0x47, 0x58, 0xfb, 0x97, 0xd0, 0x7d, 0xfd, 0x7f, 0xa7, 0x84,
	0x1b, 0xaf, 0xc4, 0xb8, 0xb4, 0x75, 0x4b, 0x70, 0xf5, 0x6d, 0x5e, 0x82, 0x5b, 0x58, 0xdc, 0xbc,
	0x32, 0xf8, 0x6b, 0xc2, 0x26, 0xf9, 0xa4, 0x4f, 0x38, 0x81, 0xea, 0x68, 0x26, 0x99, 0xb5, 0x32,
	0x3e, 0x29, 0xf6, 0xf6, 0x9a, 0x9b, 0x8c, 0xe8, 0x09, 0x54, 0x2f, 0x71, 0x25, 0x7a, 0x39, 0x30,
	0xc5, 0xe8, 0xdc, 0x94, 0xf0, 0x0a, 0x1b, 0x42, 0x23, 0x91, 0x23, 0xdb, 0xd1, 0xdd, 0x34, 0x99,
	0x77, 0x77, 0xd7, 0x5f, 0xe6, 0x61, 0x12, 0xa1, 0x15, 0x61, 0x34, 0x99, 0x16, 0x61, 0x74, 0x6d,
	0xf2, 0x0a, 0xbb, 0x82, 0x56, 0x2a, 0x13, 0x56, 0xd8, 0x26, 0x05, 0x09, 0x76, 0x5f, 0x95, 0x5d,
	0xa7, 0x60, 0xd7, 0x0d, 0xe5, 0x70, 0xf4, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x70, 0xf7, 0xb8,
	0x9c, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MessageBackendServiceClient is the client API for MessageBackendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessageBackendServiceClient interface {
	Approve(ctx context.Context, in *MessageBackendApproveRequest, opts ...grpc.CallOption) (*MessageBackendApproveResponse, error)
	Deliver(ctx context.Context, in *MessageBackendDeliverRequest, opts ...grpc.CallOption) (*MessageBackendDeliverResponse, error)
}

type messageBackendServiceClient struct {
	cc *grpc.ClientConn
}

func NewMessageBackendServiceClient(cc *grpc.ClientConn) MessageBackendServiceClient {
	return &messageBackendServiceClient{cc}
}

func (c *messageBackendServiceClient) Approve(ctx context.Context, in *MessageBackendApproveRequest, opts ...grpc.CallOption) (*MessageBackendApproveResponse, error) {
	out := new(MessageBackendApproveResponse)
	err := c.cc.Invoke(ctx, "/proto.MessageBackendService/Approve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBackendServiceClient) Deliver(ctx context.Context, in *MessageBackendDeliverRequest, opts ...grpc.CallOption) (*MessageBackendDeliverResponse, error) {
	out := new(MessageBackendDeliverResponse)
	err := c.cc.Invoke(ctx, "/proto.MessageBackendService/Deliver", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageBackendServiceServer is the server API for MessageBackendService service.
type MessageBackendServiceServer interface {
	Approve(context.Context, *MessageBackendApproveRequest) (*MessageBackendApproveResponse, error)
	Deliver(context.Context, *MessageBackendDeliverRequest) (*MessageBackendDeliverResponse, error)
}

func RegisterMessageBackendServiceServer(s *grpc.Server, srv MessageBackendServiceServer) {
	s.RegisterService(&_MessageBackendService_serviceDesc, srv)
}

func _MessageBackendService_Approve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageBackendApproveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBackendServiceServer).Approve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MessageBackendService/Approve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBackendServiceServer).Approve(ctx, req.(*MessageBackendApproveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBackendService_Deliver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageBackendDeliverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBackendServiceServer).Deliver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MessageBackendService/Deliver",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBackendServiceServer).Deliver(ctx, req.(*MessageBackendDeliverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MessageBackendService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MessageBackendService",
	HandlerType: (*MessageBackendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Approve",
			Handler:    _MessageBackendService_Approve_Handler,
		},
		{
			MethodName: "Deliver",
			Handler:    _MessageBackendService_Deliver_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/messages.proto",
}

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessageServiceClient interface {
	Put(ctx context.Context, in *MessagePutRequest, opts ...grpc.CallOption) (*MessagePutResponse, error)
	Get(ctx context.Context, in *MessageGetRequest, opts ...grpc.CallOption) (*MessageGetResponse, error)
	Update(ctx context.Context, in *MessageUpdateRequest, opts ...grpc.CallOption) (*MessageUpdateResponse, error)
	Cancel(ctx context.Context, in *MessageCancelRequest, opts ...grpc.CallOption) (*MessageCancelResponse, error)
	Register(ctx context.Context, in *MessageRegisterRequest, opts ...grpc.CallOption) (*MessageRegisterResponse, error)
}

type messageServiceClient struct {
	cc *grpc.ClientConn
}

func NewMessageServiceClient(cc *grpc.ClientConn) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) Put(ctx context.Context, in *MessagePutRequest, opts ...grpc.CallOption) (*MessagePutResponse, error) {
	out := new(MessagePutResponse)
	err := c.cc.Invoke(ctx, "/proto.MessageService/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) Get(ctx context.Context, in *MessageGetRequest, opts ...grpc.CallOption) (*MessageGetResponse, error) {
	out := new(MessageGetResponse)
	err := c.cc.Invoke(ctx, "/proto.MessageService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) Update(ctx context.Context, in *MessageUpdateRequest, opts ...grpc.CallOption) (*MessageUpdateResponse, error) {
	out := new(MessageUpdateResponse)
	err := c.cc.Invoke(ctx, "/proto.MessageService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) Cancel(ctx context.Context, in *MessageCancelRequest, opts ...grpc.CallOption) (*MessageCancelResponse, error) {
	out := new(MessageCancelResponse)
	err := c.cc.Invoke(ctx, "/proto.MessageService/Cancel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) Register(ctx context.Context, in *MessageRegisterRequest, opts ...grpc.CallOption) (*MessageRegisterResponse, error) {
	out := new(MessageRegisterResponse)
	err := c.cc.Invoke(ctx, "/proto.MessageService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServiceServer is the server API for MessageService service.
type MessageServiceServer interface {
	Put(context.Context, *MessagePutRequest) (*MessagePutResponse, error)
	Get(context.Context, *MessageGetRequest) (*MessageGetResponse, error)
	Update(context.Context, *MessageUpdateRequest) (*MessageUpdateResponse, error)
	Cancel(context.Context, *MessageCancelRequest) (*MessageCancelResponse, error)
	Register(context.Context, *MessageRegisterRequest) (*MessageRegisterResponse, error)
}

func RegisterMessageServiceServer(s *grpc.Server, srv MessageServiceServer) {
	s.RegisterService(&_MessageService_serviceDesc, srv)
}

func _MessageService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessagePutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MessageService/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).Put(ctx, req.(*MessagePutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MessageService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).Get(ctx, req.(*MessageGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MessageService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).Update(ctx, req.(*MessageUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageCancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MessageService/Cancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).Cancel(ctx, req.(*MessageCancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MessageService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).Register(ctx, req.(*MessageRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MessageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _MessageService_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _MessageService_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _MessageService_Update_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _MessageService_Cancel_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _MessageService_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/messages.proto",
}
