// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/messages.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessagesError struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessagesError) Reset()         { *m = MessagesError{} }
func (m *MessagesError) String() string { return proto.CompactTextString(m) }
func (*MessagesError) ProtoMessage()    {}
func (*MessagesError) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{0}
}

func (m *MessagesError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagesError.Unmarshal(m, b)
}
func (m *MessagesError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagesError.Marshal(b, m, deterministic)
}
func (m *MessagesError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesError.Merge(m, src)
}
func (m *MessagesError) XXX_Size() int {
	return xxx_messageInfo_MessagesError.Size(m)
}
func (m *MessagesError) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesError.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesError proto.InternalMessageInfo

func (m *MessagesError) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *MessagesError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Message struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Channel              string   `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Provider             string   `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Message) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *Message) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *Message) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Message) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type Channel struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Providers            []*Provider `protobuf:"bytes,2,rep,name=providers,proto3" json:"providers,omitempty"`
	Host                 string      `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port                 string      `protobuf:"bytes,4,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Channel) Reset()         { *m = Channel{} }
func (m *Channel) String() string { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()    {}
func (*Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{2}
}

func (m *Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Channel.Unmarshal(m, b)
}
func (m *Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Channel.Marshal(b, m, deterministic)
}
func (m *Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Channel.Merge(m, src)
}
func (m *Channel) XXX_Size() int {
	return xxx_messageInfo_Channel.Size(m)
}
func (m *Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_Channel proto.InternalMessageInfo

func (m *Channel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Channel) GetProviders() []*Provider {
	if m != nil {
		return m.Providers
	}
	return nil
}

func (m *Channel) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Channel) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type Provider struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Params               map[string]string `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Provider) Reset()         { *m = Provider{} }
func (m *Provider) String() string { return proto.CompactTextString(m) }
func (*Provider) ProtoMessage()    {}
func (*Provider) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{3}
}

func (m *Provider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Provider.Unmarshal(m, b)
}
func (m *Provider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Provider.Marshal(b, m, deterministic)
}
func (m *Provider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Provider.Merge(m, src)
}
func (m *Provider) XXX_Size() int {
	return xxx_messageInfo_Provider.Size(m)
}
func (m *Provider) XXX_DiscardUnknown() {
	xxx_messageInfo_Provider.DiscardUnknown(m)
}

var xxx_messageInfo_Provider proto.InternalMessageInfo

func (m *Provider) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Provider) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

type MessagePutRequest struct {
	Channel              string   `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Provider             string   `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Delay                int64    `protobuf:"varint,4,opt,name=delay,proto3" json:"delay,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessagePutRequest) Reset()         { *m = MessagePutRequest{} }
func (m *MessagePutRequest) String() string { return proto.CompactTextString(m) }
func (*MessagePutRequest) ProtoMessage()    {}
func (*MessagePutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{4}
}

func (m *MessagePutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagePutRequest.Unmarshal(m, b)
}
func (m *MessagePutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagePutRequest.Marshal(b, m, deterministic)
}
func (m *MessagePutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagePutRequest.Merge(m, src)
}
func (m *MessagePutRequest) XXX_Size() int {
	return xxx_messageInfo_MessagePutRequest.Size(m)
}
func (m *MessagePutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagePutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessagePutRequest proto.InternalMessageInfo

func (m *MessagePutRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *MessagePutRequest) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *MessagePutRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MessagePutRequest) GetDelay() int64 {
	if m != nil {
		return m.Delay
	}
	return 0
}

type MessagePutDataResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessagePutDataResponse) Reset()         { *m = MessagePutDataResponse{} }
func (m *MessagePutDataResponse) String() string { return proto.CompactTextString(m) }
func (*MessagePutDataResponse) ProtoMessage()    {}
func (*MessagePutDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{5}
}

func (m *MessagePutDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagePutDataResponse.Unmarshal(m, b)
}
func (m *MessagePutDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagePutDataResponse.Marshal(b, m, deterministic)
}
func (m *MessagePutDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagePutDataResponse.Merge(m, src)
}
func (m *MessagePutDataResponse) XXX_Size() int {
	return xxx_messageInfo_MessagePutDataResponse.Size(m)
}
func (m *MessagePutDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagePutDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessagePutDataResponse proto.InternalMessageInfo

func (m *MessagePutDataResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MessagePutResponse struct {
	Data                 *MessagePutDataResponse `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                *MessagesError          `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *MessagePutResponse) Reset()         { *m = MessagePutResponse{} }
func (m *MessagePutResponse) String() string { return proto.CompactTextString(m) }
func (*MessagePutResponse) ProtoMessage()    {}
func (*MessagePutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{6}
}

func (m *MessagePutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagePutResponse.Unmarshal(m, b)
}
func (m *MessagePutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagePutResponse.Marshal(b, m, deterministic)
}
func (m *MessagePutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagePutResponse.Merge(m, src)
}
func (m *MessagePutResponse) XXX_Size() int {
	return xxx_messageInfo_MessagePutResponse.Size(m)
}
func (m *MessagePutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagePutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessagePutResponse proto.InternalMessageInfo

func (m *MessagePutResponse) GetData() *MessagePutDataResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *MessagePutResponse) GetError() *MessagesError {
	if m != nil {
		return m.Error
	}
	return nil
}

type MessageGetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageGetRequest) Reset()         { *m = MessageGetRequest{} }
func (m *MessageGetRequest) String() string { return proto.CompactTextString(m) }
func (*MessageGetRequest) ProtoMessage()    {}
func (*MessageGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{7}
}

func (m *MessageGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageGetRequest.Unmarshal(m, b)
}
func (m *MessageGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageGetRequest.Marshal(b, m, deterministic)
}
func (m *MessageGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageGetRequest.Merge(m, src)
}
func (m *MessageGetRequest) XXX_Size() int {
	return xxx_messageInfo_MessageGetRequest.Size(m)
}
func (m *MessageGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageGetRequest proto.InternalMessageInfo

func (m *MessageGetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MessageGetResponse struct {
	Data                 *Message       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                *MessagesError `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MessageGetResponse) Reset()         { *m = MessageGetResponse{} }
func (m *MessageGetResponse) String() string { return proto.CompactTextString(m) }
func (*MessageGetResponse) ProtoMessage()    {}
func (*MessageGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{8}
}

func (m *MessageGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageGetResponse.Unmarshal(m, b)
}
func (m *MessageGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageGetResponse.Marshal(b, m, deterministic)
}
func (m *MessageGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageGetResponse.Merge(m, src)
}
func (m *MessageGetResponse) XXX_Size() int {
	return xxx_messageInfo_MessageGetResponse.Size(m)
}
func (m *MessageGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageGetResponse proto.InternalMessageInfo

func (m *MessageGetResponse) GetData() *Message {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *MessageGetResponse) GetError() *MessagesError {
	if m != nil {
		return m.Error
	}
	return nil
}

type MessageUpdateRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageUpdateRequest) Reset()         { *m = MessageUpdateRequest{} }
func (m *MessageUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*MessageUpdateRequest) ProtoMessage()    {}
func (*MessageUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{9}
}

func (m *MessageUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageUpdateRequest.Unmarshal(m, b)
}
func (m *MessageUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageUpdateRequest.Marshal(b, m, deterministic)
}
func (m *MessageUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageUpdateRequest.Merge(m, src)
}
func (m *MessageUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_MessageUpdateRequest.Size(m)
}
func (m *MessageUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageUpdateRequest proto.InternalMessageInfo

func (m *MessageUpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageUpdateRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type MessageUpdateResponse struct {
	Error                *MessagesError `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MessageUpdateResponse) Reset()         { *m = MessageUpdateResponse{} }
func (m *MessageUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*MessageUpdateResponse) ProtoMessage()    {}
func (*MessageUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{10}
}

func (m *MessageUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageUpdateResponse.Unmarshal(m, b)
}
func (m *MessageUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageUpdateResponse.Marshal(b, m, deterministic)
}
func (m *MessageUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageUpdateResponse.Merge(m, src)
}
func (m *MessageUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_MessageUpdateResponse.Size(m)
}
func (m *MessageUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageUpdateResponse proto.InternalMessageInfo

func (m *MessageUpdateResponse) GetError() *MessagesError {
	if m != nil {
		return m.Error
	}
	return nil
}

type MessageCancelRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageCancelRequest) Reset()         { *m = MessageCancelRequest{} }
func (m *MessageCancelRequest) String() string { return proto.CompactTextString(m) }
func (*MessageCancelRequest) ProtoMessage()    {}
func (*MessageCancelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{11}
}

func (m *MessageCancelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageCancelRequest.Unmarshal(m, b)
}
func (m *MessageCancelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageCancelRequest.Marshal(b, m, deterministic)
}
func (m *MessageCancelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageCancelRequest.Merge(m, src)
}
func (m *MessageCancelRequest) XXX_Size() int {
	return xxx_messageInfo_MessageCancelRequest.Size(m)
}
func (m *MessageCancelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageCancelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageCancelRequest proto.InternalMessageInfo

func (m *MessageCancelRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MessageCancelResponse struct {
	Error                *MessagesError `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MessageCancelResponse) Reset()         { *m = MessageCancelResponse{} }
func (m *MessageCancelResponse) String() string { return proto.CompactTextString(m) }
func (*MessageCancelResponse) ProtoMessage()    {}
func (*MessageCancelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_346d92f49d8efbd3, []int{12}
}

func (m *MessageCancelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageCancelResponse.Unmarshal(m, b)
}
func (m *MessageCancelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageCancelResponse.Marshal(b, m, deterministic)
}
func (m *MessageCancelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageCancelResponse.Merge(m, src)
}
func (m *MessageCancelResponse) XXX_Size() int {
	return xxx_messageInfo_MessageCancelResponse.Size(m)
}
func (m *MessageCancelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageCancelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageCancelResponse proto.InternalMessageInfo

func (m *MessageCancelResponse) GetError() *MessagesError {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*MessagesError)(nil), "proto.MessagesError")
	proto.RegisterType((*Message)(nil), "proto.Message")
	proto.RegisterType((*Channel)(nil), "proto.Channel")
	proto.RegisterType((*Provider)(nil), "proto.Provider")
	proto.RegisterMapType((map[string]string)(nil), "proto.Provider.ParamsEntry")
	proto.RegisterType((*MessagePutRequest)(nil), "proto.MessagePutRequest")
	proto.RegisterType((*MessagePutDataResponse)(nil), "proto.MessagePutDataResponse")
	proto.RegisterType((*MessagePutResponse)(nil), "proto.MessagePutResponse")
	proto.RegisterType((*MessageGetRequest)(nil), "proto.MessageGetRequest")
	proto.RegisterType((*MessageGetResponse)(nil), "proto.MessageGetResponse")
	proto.RegisterType((*MessageUpdateRequest)(nil), "proto.MessageUpdateRequest")
	proto.RegisterType((*MessageUpdateResponse)(nil), "proto.MessageUpdateResponse")
	proto.RegisterType((*MessageCancelRequest)(nil), "proto.MessageCancelRequest")
	proto.RegisterType((*MessageCancelResponse)(nil), "proto.MessageCancelResponse")
}

func init() { proto.RegisterFile("proto/messages.proto", fileDescriptor_346d92f49d8efbd3) }

var fileDescriptor_346d92f49d8efbd3 = []byte{
	// 535 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0x6d, 0x92, 0xa6, 0xdd, 0xde, 0xe2, 0xba, 0x0e, 0x71, 0x89, 0x5d, 0x85, 0x32, 0x82, 0x14,
	0xc1, 0x8a, 0xdd, 0x17, 0x15, 0x05, 0xa1, 0x96, 0x7d, 0x12, 0xca, 0x14, 0x3f, 0x60, 0x4c, 0x2e,
	0xb6, 0x98, 0x26, 0x71, 0x66, 0x52, 0xe8, 0xa3, 0x3f, 0xe0, 0x17, 0xf8, 0xb1, 0x92, 0xc9, 0x24,
	0x4d, 0xd2, 0x16, 0x71, 0x9f, 0x72, 0xef, 0xdc, 0x7b, 0xce, 0x3d, 0x9c, 0x13, 0xf0, 0x52, 0x91,
	0xa8, 0xe4, 0xf5, 0x16, 0xa5, 0xe4, 0xdf, 0x51, 0x4e, 0x75, 0x4b, 0x5c, 0xfd, 0xa1, 0x1f, 0xe1,
	0xc1, 0x17, 0x33, 0x58, 0x08, 0x91, 0x08, 0x42, 0xa0, 0x1b, 0x24, 0x21, 0xfa, 0xd6, 0xd8, 0x9a,
	0xb8, 0x4c, 0xd7, 0xc4, 0x87, 0xbe, 0x41, 0xfb, 0xf6, 0xd8, 0x9a, 0x0c, 0x58, 0xd9, 0xd2, 0x5f,
	0x16, 0xf4, 0x0d, 0x9e, 0x5c, 0x82, 0xbd, 0x09, 0x35, 0x6e, 0xc0, 0xec, 0x4d, 0x98, 0xa3, 0x82,
	0x35, 0x8f, 0x63, 0x8c, 0x4a, 0x94, 0x69, 0xc9, 0x08, 0x2e, 0x52, 0x91, 0xec, 0x36, 0x21, 0x0a,
	0xdf, 0xd1, 0xa3, 0xaa, 0xd7, 0xa8, 0x24, 0x56, 0x18, 0x2b, 0xbf, 0x6b, 0x50, 0x45, 0x4b, 0xae,
	0xa1, 0x27, 0x15, 0x57, 0x99, 0xf4, 0x5d, 0x3d, 0x30, 0x1d, 0x55, 0xd0, 0x9f, 0x1b, 0x62, 0x02,
	0xdd, 0x98, 0x6f, 0xd1, 0x88, 0xd0, 0x35, 0x79, 0x05, 0x83, 0x92, 0x5c, 0xfa, 0xf6, 0xd8, 0x99,
	0x0c, 0x67, 0x0f, 0x0b, 0x0f, 0xa6, 0x4b, 0xf3, 0xce, 0x0e, 0x1b, 0x39, 0xc5, 0x3a, 0x91, 0xca,
	0xe8, 0xd2, 0x75, 0xfe, 0x96, 0x26, 0xa2, 0x14, 0xa4, 0x6b, 0xfa, 0xdb, 0x82, 0x8b, 0x12, 0x7f,
	0xf2, 0xee, 0x2d, 0xf4, 0x52, 0x2e, 0xf8, 0xb6, 0x3c, 0x7a, 0xd3, 0x3a, 0x3a, 0x5d, 0xea, 0xe9,
	0x22, 0x56, 0x62, 0xcf, 0xcc, 0xea, 0xe8, 0x1d, 0x0c, 0x6b, 0xcf, 0xe4, 0x0a, 0x9c, 0x1f, 0xb8,
	0x37, 0xb4, 0x79, 0x49, 0x3c, 0x70, 0x77, 0x3c, 0xca, 0xca, 0x20, 0x8a, 0xe6, 0xbd, 0xfd, 0xd6,
	0xa2, 0x7b, 0x78, 0x64, 0x92, 0x58, 0x66, 0x8a, 0xe1, 0xcf, 0x0c, 0xa5, 0xaa, 0x67, 0x60, 0x9d,
	0xcf, 0xc0, 0x3e, 0x9f, 0x81, 0xd3, 0xcc, 0xc0, 0x03, 0x37, 0xc4, 0x88, 0xef, 0xb5, 0x15, 0x0e,
	0x2b, 0x1a, 0x3a, 0x81, 0xeb, 0xc3, 0xe9, 0xcf, 0x5c, 0x71, 0x86, 0x32, 0x4d, 0x62, 0x79, 0xf4,
	0x4f, 0x50, 0x09, 0xa4, 0x2e, 0xd2, 0x6c, 0xbd, 0x81, 0x6e, 0xc8, 0x15, 0xd7, 0x7b, 0xc3, 0xd9,
	0x33, 0x63, 0xd4, 0x69, 0x4a, 0xa6, 0x57, 0xc9, 0x4b, 0x70, 0x31, 0xff, 0x5f, 0xb5, 0xf6, 0xe1,
	0xcc, 0x6b, 0x62, 0x8a, 0x7f, 0x99, 0x15, 0x2b, 0xf4, 0x79, 0xe5, 0xcc, 0x1d, 0x56, 0xce, 0xb4,
	0x95, 0x85, 0x95, 0x32, 0xbd, 0x64, 0x94, 0xd1, 0x86, 0xb2, 0xcb, 0xe6, 0x95, 0x7b, 0x48, 0xf9,
	0x04, 0x9e, 0x79, 0xff, 0x9a, 0x86, 0x5c, 0xe1, 0x19, 0x35, 0xf5, 0x04, 0xec, 0x46, 0x02, 0x74,
	0x0e, 0x8f, 0x5b, 0x0c, 0x46, 0x6a, 0x25, 0xc3, 0xfa, 0xb7, 0x8c, 0x17, 0x95, 0x8c, 0x39, 0x8f,
	0x03, 0x8c, 0xce, 0x99, 0x72, 0x38, 0x56, 0xee, 0xfd, 0xff, 0xb1, 0xd9, 0x1f, 0x1b, 0xae, 0x56,
	0xc1, 0x1a, 0xc3, 0x2c, 0x42, 0xb1, 0x42, 0xb1, 0xdb, 0x04, 0x48, 0x3e, 0x80, 0xb3, 0xcc, 0x14,
	0xf1, 0x8f, 0xb2, 0x36, 0x52, 0x46, 0x4f, 0x4e, 0x4c, 0x8a, 0xe3, 0xb4, 0x93, 0xa3, 0xef, 0xf0,
	0x08, 0x7d, 0x48, 0xb7, 0x8d, 0xae, 0x45, 0x4a, 0x3b, 0x64, 0x01, 0xbd, 0xc2, 0x3b, 0x72, 0xd3,
	0x5c, 0x6b, 0x64, 0x32, 0x7a, 0x7a, 0x7a, 0x58, 0xa7, 0x29, 0x5c, 0x69, 0xd3, 0x34, 0x3c, 0x6d,
	0xd3, 0x34, 0x8d, 0xa4, 0x9d, 0x6f, 0x3d, 0x3d, 0xbe, 0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xd9,
	0xae, 0xf5, 0x28, 0xa7, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SchedulerServiceClient is the client API for SchedulerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SchedulerServiceClient interface {
	Put(ctx context.Context, in *MessagePutRequest, opts ...grpc.CallOption) (*MessagePutResponse, error)
	Get(ctx context.Context, in *MessageGetRequest, opts ...grpc.CallOption) (*MessageGetResponse, error)
	Update(ctx context.Context, in *MessageUpdateRequest, opts ...grpc.CallOption) (*MessageUpdateResponse, error)
	Cancel(ctx context.Context, in *MessageCancelRequest, opts ...grpc.CallOption) (*MessageCancelResponse, error)
}

type schedulerServiceClient struct {
	cc *grpc.ClientConn
}

func NewSchedulerServiceClient(cc *grpc.ClientConn) SchedulerServiceClient {
	return &schedulerServiceClient{cc}
}

func (c *schedulerServiceClient) Put(ctx context.Context, in *MessagePutRequest, opts ...grpc.CallOption) (*MessagePutResponse, error) {
	out := new(MessagePutResponse)
	err := c.cc.Invoke(ctx, "/proto.SchedulerService/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) Get(ctx context.Context, in *MessageGetRequest, opts ...grpc.CallOption) (*MessageGetResponse, error) {
	out := new(MessageGetResponse)
	err := c.cc.Invoke(ctx, "/proto.SchedulerService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) Update(ctx context.Context, in *MessageUpdateRequest, opts ...grpc.CallOption) (*MessageUpdateResponse, error) {
	out := new(MessageUpdateResponse)
	err := c.cc.Invoke(ctx, "/proto.SchedulerService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) Cancel(ctx context.Context, in *MessageCancelRequest, opts ...grpc.CallOption) (*MessageCancelResponse, error) {
	out := new(MessageCancelResponse)
	err := c.cc.Invoke(ctx, "/proto.SchedulerService/Cancel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulerServiceServer is the server API for SchedulerService service.
type SchedulerServiceServer interface {
	Put(context.Context, *MessagePutRequest) (*MessagePutResponse, error)
	Get(context.Context, *MessageGetRequest) (*MessageGetResponse, error)
	Update(context.Context, *MessageUpdateRequest) (*MessageUpdateResponse, error)
	Cancel(context.Context, *MessageCancelRequest) (*MessageCancelResponse, error)
}

func RegisterSchedulerServiceServer(s *grpc.Server, srv SchedulerServiceServer) {
	s.RegisterService(&_SchedulerService_serviceDesc, srv)
}

func _SchedulerService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessagePutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SchedulerService/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).Put(ctx, req.(*MessagePutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SchedulerService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).Get(ctx, req.(*MessageGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SchedulerService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).Update(ctx, req.(*MessageUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageCancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SchedulerService/Cancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).Cancel(ctx, req.(*MessageCancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SchedulerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SchedulerService",
	HandlerType: (*SchedulerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _SchedulerService_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _SchedulerService_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _SchedulerService_Update_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _SchedulerService_Cancel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/messages.proto",
}
